Fixing lab5 build errors
For some reason, after checking out lab5 source, merging in lab4 work, and then compiling test programs from lab4 (after commenting out `ENV_CREATE(fs_fs...)` in `kern/init.c` and `close_all()` in `lib/exit.c`, we get the following build errors (one after another):

1. Unaligned pointer error
```
make[1]: Entering directory '/home/david/6.828/jos'
+ cc[USER] lib/spawn.c
lib/spawn.c: In function ‘spawn’:
lib/spawn.c:110:42: error: taking address of packed member of ‘struct Trapframe’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  110 |         if ((r = init_stack(child, argv, (uintptr_t *)&child_tf.tf_esp)) < 0)
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [lib/Makefrag:37: obj/lib/spawn.o] Error 1
make[1]: Leaving directory '/home/david/6.828/jos'
make: *** [GNUmakefile:313: prep-primes] Error 2
```

Referring to `https://github.com/fisop/jos/issues/3`, this user added a CFLAGS `-Wno-address-of-packed-member` into GNUmakefile, and resolved this issue, leading to the next issue...

2. Multiple definitions defined
```
ld: obj/fs/bc.o: in function `bc_pgfault':22
fs/bc.c:31: multiple definition of `super'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/bc.o: in function `bc_pgfault':
fs/bc.c:31: multiple definition of `bitmap'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/fs.o: in function `walk_path':
fs/fs.c:233: multiple definition of `super'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/fs.o: in function `walk_path':
fs/fs.c:233: multiple definition of `bitmap'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/serv.o: in function `serve_read':
fs/serv.c:218: multiple definition of `bitmap'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/serv.o: in function `serve_read':
fs/serv.c:218: multiple definition of `super'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/test.o: in function `fs_test':
fs/test.c:10: multiple definition of `bitmap'; obj/fs/ide.o:fs/ide.c:19: first defined here
ld: obj/fs/test.o: in function `fs_test':
fs/test.c:10: multiple definition of `super'; obj/fs/ide.o:fs/ide.c:19: first defined here
make[1]: *** [fs/Makefrag:52: obj/fs/fs] Error 1
make[1]: Leaving directory '/home/david/6.828/jos'
make: *** [GNUmakefile:316: prep-forktree] Error 2
```

From this chinese forum (you will need to use Google translate to translate it) `https://blog.csdn.net/weixin_52877213/article/details/127109658`, you need to define the `super` and `bitmap` pointers in `fs/fs.c` and in `fs/fs.h` and set both pointers to `extern` instead. This will (in addition  to temporarily commenting out the two calls as mentioned in lab5) will allow you run the test programs.

You'd think that this would've been solved and fixed already by the lab instructor but ¯\_(ツ)_/¯